#!/bin/bash
SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`

#INSTALL_ROOT_DIR="$SCRIPTPATH/../install"
#INSTALL_ROOT_DIR="$HOME/install"
THREAD_NUM=4
#DATE="$(date +%Y%m%d%H%M)"
DATE="$(date +%Y%m%d)"
. ./system.config
. ./base.bash

[ ! -z ${NAME+x} ] || die "Variable NAME not defined"
[ ! -z ${VERSION+x} ] || die "Variable VERSION not defined"
[ ! -z ${DATE+x} ] || DATE="$(date +%Y%m%d)"

if [ "git" == "$VERSION" ] || [ "svn" == "$VERSION" ]; then
	VERSION="${VERSION}-${DATE}"
fi

# Install root dir
#ROOT_DIR="${SCRIPTPATH}/.."
ROOT_DIR="${HOME}/software"
INSTALL_ROOT_DIR="${ROOT_DIR}/install"
[ ! -d "${INSTALL_ROOT_DIR}" ] && mkdir -p ${INSTALL_ROOT_DIR}
INSTALL_ROOT_DIR="$(readlink -f ${INSTALL_ROOT_DIR})"

# Cache
CACHEdir="${ROOT_DIR}/cache"
[ ! -d "${CACHEdir}" ] && mkdir -p ${CACHEdir}
CACHEdir="$(readlink -f ${CACHEdir})"

# Source
SRCdir="${CACHEdir}/${NAME}/${VERSION}" 		# source directory
[ ! -d "${SRCdir}" ] && mkdir -p ${SRCdir}
BLDdir="${SRCdir}/build" 			# build directory
if [[ $LABEL != "" ]]; then
  PREFIX="${INSTALL_ROOT_DIR}/${NAME}/${VERSION}-${LABEL}"		# install directory
else
  PREFIX="${INSTALL_ROOT_DIR}/${NAME}/${VERSION}"		# install directory
fi

# Modules
MPATH="${ROOT_DIR}/modules/${USER}"
[ ! -d "${MPATH}" ] && mkdir -p ${MPATH}
MPATH="$(readlink -f ${MPATH})"

if [[ $LABEL != "" ]]; then
  MFILE="${MPATH}/${NAME}/${VERSION}-${LABEL}"
else
  MFILE="${MPATH}/${NAME}/${VERSION}"
fi

[ ! -d "$(dirname ${MFILE})" ] && mkdir -p $(dirname ${MFILE})

export MODULEPATH="${MPATH}:$MODULEPATH"


# Others
THREAD_NUM=8

## Print paths ##

WIDTH=20 
echo "INSTALL SUMMARY:"
echo "================"
printf "\t%-*s: %s\n" ${WIDTH} "NAME:" "${NAME}"
printf "\t%-*s: %s\n" ${WIDTH} "VERSION:" "${VERSION}"
printf "\t%-*s: %s\n" ${WIDTH} "CACHE:" "${CACHEdir}" 
printf "\t%-*s: %s\n" ${WIDTH} "SOURCE:" "${SRCdir}"
printf "\t%-*s: %s\n" ${WIDTH} "BUILD:" "${BLDdir}"
printf "\t%-*s: %s\n" ${WIDTH} "INSTALL_ROOT_DIR:" "${INSTALL_ROOT_DIR}"
printf "\t%-*s: %s\n" ${WIDTH} "INSTALL:" "${PREFIX}"
printf "\t%-*s: %s\n" ${WIDTH} "MPATH:" "${MPATH}"
printf "\t%-*s: %s\n" ${WIDTH} "MFILE:" "${MFILE}"
