#!/bin/bash

export NAME="netcdf_fortran"
export VERSION="4.4.4"
source ./config

fetch_http "ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.4.tar.gz"

declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" )

function build_script {
	set -x
 cd netcdf-fortran-$VERSION
 module_load "${deps[@]}"

 CC=$(which mpicc) 
 CXX=$(which mpicxx)
 FF=$(which mpif90)
 FC=$(which mpif90)

 ./configure --prefix=$PREFIX || die "Couldn't configure"

 make -j $THREAD_NUM || die "Couldn't make"
 make install  -j $THREAD_NUM || die "Couldn't install"
 set +x
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
