#!/bin/bash

export NAME="ior"
export VERSION="git"
source ./config
fetch_git "https://github.com/hpc/ior.git"
declare -a deps=( "hdf5/1.10.4" )

function build_script {
    ./bootstrap
    H5DIR="$(readlink -f $(dirname $(which h5dump))/..)"
    MPIDIR="$(readlink -f $(dirname $(which mpiexec))/..)"
    set -x
    make clean

    #export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/include"
    #export LDFLAGS="-Wl,-rpath=${MPIDIR}/lib -L${MPIDIR}/lib -L${H5DIR}/lib -lgpfs" 
    #export CPPFLAGS="-I${MPIDIR}/include -I${H5DIR}/include -I/usr/include"

    ./configure \
        --prefix="${PREFIX}" \
        --with-posix \
        --with-mpiio || die "Configure failed"

        #--with-lustre \
        #--with-ime \

    set +x
    make -j${THREAD_NUM} || die "Make failde"
    make install || die "Install failed"
}


build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths

