#!/bin/bash

export NAME="paraview-thirdparty"
export VERSION="nik-flo-merge-attempt1"
source ./config
#declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" )
 #"smd/git-20210217" )

declare -a load=( \
   "zlib-1.2.11-gcc-10.2.0-ukah6om" \
   "automake-1.16.3-gcc-10.2.0-kb4v4li" \
   "gettext-0.21-gcc-10.2.0-b25zrek" \
   "libtool-2.4.6-gcc-10.2.0-oq2xmcq" \
   "autoconf-2.69-gcc-10.2.0-so25e4q" \
   "gcc-10.2.0-gcc-7.1.0-3o6mwwu" \
   "cmake-3.19.5-gcc-10.2.0-nktbmrb" \
   "pcre-8.44-gcc-10.2.0-vbysbfg" \
   "binutils-2.35.1-gcc-7.1.0-h6oupkx" \
   "pkgconf-1.7.3-gcc-10.2.0-oub6luh" \
   )

declare -a deps=( \
    ) 
    #"k202107/python/2.7.15" \
    #"k202107/pcre/8.44" \
    #"k202107/glib/2.56.4" \

#set -x
#fetch_local_dir "/mnt/lustre02/work/kv0653/k202134/Paraview/nik-flo-merge-attempt1/ThirdParty/CDI"
#fetch_local_dir "/mnt/lustre02/work/kv0653/k202134/Paraview/nik-flo-merge-attempt1/"

function build_script {
    module_load "${load[@]}"
	module_load "${deps[@]}"

    pwd
    cd CDI
    cmake --version

    [ -d "build" ] && rm -r build 
    mkdir build
    cd build

    cmake -DCMAKE_INSTALL_PREFIX=$PREFIX ..

  #  ESDMPATH="$(dirname $(which mkfs.esdm))/.."

  #  autoreconf --install --force

  #  ./configure \
  #    --prefix=$PREFIX \
  #    --with-esdm=$ESDMPATH \
  #    LDFLAGS="" \
  #    CFLAGS="-g3" \
  #    CC=mpicc \
  #    --disable-dap || die "configure failed"

  #    #--with-hdf5=$HOME/install \
  ##LDFLAGS="-L$HOME/install/lib" \
  ##CFLAGS="-I$HOME/install/include -g3" \

  #  make -j || die "compile failed"
  #  make install || die "install failed"

}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
