#!/bin/bash

export NAME="psyclone"
export VERSION="1.5.1"
source ./config

fetch_http "https://github.com/stfc/PSyclone/archive/$VERSION.tar.gz"

declare -a deps=( )
#declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" )

function build_script {
	set -x
	cd PSyclone-$VERSION || die "Couldn't find directory"
	module_load "${deps[@]}"

  #cp -r $SRC_DIR/PSyclone-* psyclone

  export PSYCLONE_DIR=$PREFIX
  export PATH=$PREFIX/bin:$PSYCLONE_DIR/bin:$PATH
  export PYTHONPATH=$PREFIX:$PYTHONPATH
  #cd psyclone
  ./contributions/install $PSYCLONE_DIR

	set +x
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
