#!/bin/bash

export NAME="netcdf"
export VERSION="4.5.0"
source ./config

fetch_http "ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-$VERSION.tar.gz"

declare -a deps=( "mpich/3.2" "hdf5/1.8.20" )

function build_script {
	set -x
 cd netcdf-$VERSION
 module_load "${deps[@]}"

 exists h5dump
 CC=$(which mpicc) 
 CXX=$(which mpicxx)
 FF=$(which mpif90)
 FC=$(which mpif90)

 H5DIR="$(readlink -f $(dirname $(which h5dump))/..)"
 #export LDFLAGS="-L${H5DIR}/lib -Wl,--rpath=${H5DIR}/lib"
 export LDFLAGS="-L${H5DIR}/lib"
 export CPPFLAGS="-I${H5DIR}/include"
 export CFLAGS="-I${H5DIR}/include"

./configure \
 --prefix=${PREFIX} \
 --enable-shared \
 --enable-static || die "Couldn't configure"


 make -j $THREAD_NUM || die "Couldn't make"
 make install  -j $THREAD_NUM || die "Couldn't install"
 set +x
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
