#!/bin/bash

export NAME="mosh"
export VERSION="1.3.2"
source ./config

declare -a load=( )
declare -a deps=( ) 

fetch_http "https://mosh.org/mosh-1.3.2.tar.gz"

function build_script {
  module_load "${load[@]}"
  module_load "${deps[@]}"

  cd mosh-1.3.2
  module_load "${deps[@]}"
  ./configure || die "configure failed"
  make || die "make failed"
  make install || die "install failed"
  set +x
}

build_with build_script

module_init
#module_deps "${deps[@]}"
auto_module_paths
