#!/bin/bash

export NAME="jansson"
export VERSION="2.13.1"
source ./config

declare -a deps=( "" )
deps=("")

fetch_http "https://digip.org/jansson/releases/jansson-2.13.1.tar.gz"

function build_script {
  set -x
	cd jansson-${VERSION}
	module_load "${deps[@]}"
    ./configure --prefix=$PREFIX || die "Couldn't configure"
    make || die "Couldn't make"
    make install || die "Couldn't install"
	set +x
}

build_with build_script

module_init
#module_deps "${deps[@]}"
auto_module_paths
