#!/bin/bash

export NAME="hdf5"
export VERSION="1.8.20"
source ./config

fetch_http "https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-$VERSION.tar.gz"

declare -a deps=( "mpich/3.2" )

function build_script {
 cd hdf5-$VERSION
 module_load "${deps[@]}"

./configure --prefix="${PREFIX}" \
	--enable-hl \
	--enable-production \
	--enable-fortran \
	--enable-fortran2003 \
	--enable-shared \
	--enable-static \
	--enable-parallel \
	CC="mpicc" \
	FC="mpif90" \
	F77="mpi77" \
	CXX="mpic++" || die "Couldn't configure"

 make -j $THREAD_NUM || die "Couldn't make"
 make install  -j $THREAD_NUM || die "Couldn't install"
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
