#!/bin/bash

export NAME="xz"
export VERSION="5.2.4"
source ./config

fetch_http "https://tukaani.org/xz/xz-5.2.4.tar.xz"
declare -a deps=(  )

function build_script {
	set -x
	cd xz-$VERSION
	module_load "${deps[@]}"

	./configure \
		--prefix=${PREFIX}  || die "Couldn't configure"

	make -j $THREAD_NUM || die "Couldn't make"
	make install  -j $THREAD_NUM || die "Couldn't install"
	set +x
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
