#!/bin/bash

export NAME="netcdf"
export VERSION="4.8.0"
source ./config

fetch_http "https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-c-4.8.0.tar.gz"

declare -a load=( \
  "cmake/3.19.5" \
)

declare -a deps=( \
  "openmpi/4.1.0" \
  "szip/2.1" \
  "maee/hdf5/1.12.0" \
)

function build_script {
	#set -x
 cd netcdf-c-$VERSION
 module_load "${load[@]}"
 module_load "${deps[@]}"
 module list

 CC=$(which mpicc) 
 CXX=$(which mpicxx)
 FF=$(which mpif90)
 FC=$(which mpif90)

 MPIDIR="$(readlink -f $(dirname $(which mpiexec))/..)"
 H5DIR="$(readlink -f $(dirname $(which h5dump))/..)"
 #export LDFLAGS="-L${H5DIR}/lib -Wl,--rpath=${H5DIR}/lib"
 export LDFLAGS="-L${H5DIR}/lib64"
 export CPPFLAGS="-I${H5DIR}/include -I${MPIDIR}/include"
 export CFLAGS=""

 make clean
 ./configure \
   --prefix=${PREFIX} \
   --enable-shared \
   --enable-static || die "Couldn't configure"


  make -j $THREAD_NUM || die "Couldn't make"
  make install  -j $THREAD_NUM || die "Couldn't install"
  set +x
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
