#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`
${SCRIPTPATH}/precheck

### CONFIG
NAME="curl"
MAJOR="7"
MINOR="47"
REVISION="1"
VERSION="$MAJOR.$MINOR.$REVISION"

source ${SCRIPTPATH}/config

FILE="$NAME-$MAJOR.$MINOR.$REVISION.tar.gz"

### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	wget https://curl.haxx.se/download/curl-7.47.1.tar.gz --no-check-certificate
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi

#SRCdir="$CACHEdir/$NAME-c-$VERSION"

### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then
	mkdir "${SRCdir}"
	tar -vzxf "./$FILE"
else
	echo "Warning: ${NAME}-${VERSION} is already extracted"
fi

module load betke/openssl

### COMPILE AND INSTALL ###
cd ${SRCdir}
make clean
make purge
./configure --prefix=$PREFIX \
 --enable-http \
 --enable-ftp \
 --enable-file \
 --enable-rtsp \
 --enable-proxy \
 --enable-dict \
 --enable-telnet \
 --enable-tftp \
 --enable-pop3 \
 --enable-imap \
 --enable-smb \
 --enable-smtp \
 --enable-gopher \
 --enable-manual \
 --enable-libcurl-option \
 --enable-libgcc \
 --enable-ipv6 \
 --enable-versioned-symbo \
 --enable-threaded-resolv \
 --enable-verbose \
 --enable-sspi \
 --enable-crypto-auth \
 --enable-tls-srp \
 --enable-unix-sockets \
 --enable-cookies \
 --enable-soname-bump \
 --with-winssl \
 --with-darwinssl 
	#--with-ssl=/work/ku0598/k202107/software/install/openssl/1.0.2f/bin/openssl
  #--enable-ntlm-wb[=FILE] 

  #--with-zlib=PATH        
  #--with-ldap-lib=libname 
  #--with-lber-lib=libname 
  #--with-gssapi-includes=D
                          
  #--with-gssapi-libs=DIR  
  #--with-gssapi=DIR       
                          
  #--with-egd-socket=FILE  
  #--with-random=FILE      
  #--with-gnutls=PATH      
  #--with-polarssl=PATH    
  #--with-mbedtls=PATH     
  #--with-cyassl=PATH      
  #--with-nss=PATH         
  #--with-axtls=PATH       
  #--with-ca-bundle=FILE   
  #--with-ca-path=DIRECTORY
  #--with-libmetalink=PATH 
  #--with-libssh2=PATH     
  #--with-librtmp=PATH     
  #--with-winidn=PATH      
  #--with-libidn=PATH      
  #--with-nghttp2=PATH     
  #--with-zsh-functions-dir
                          
                          

make -j${THREAD_NUM}
make install


### LINK ###
#source ${SCRIPTPATH}/link
