#!/bin/bash

module purge
module load ddn/mvapich/3.1.4
module load betke/hdf5/1.8.20-ddn
module list


SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`


export NAME="ior"
#export MAJOR="1"
#export MINOR="10"
#export REVISION="0-alpha0"
#export VERSION="$MAJOR.$MINOR.$REVISION"
export VERSION="git"


source ${SCRIPTPATH}/config

### CLONE ###
if [ ! -d "${CACHEDdir}/${SRCdir}" ]
then  
	mkdir "${CACHEDIR}/$SRCdir"
    git clone https://github.com/hpc/ior.git "${CACHEDIR}/$SRCdir"
else
	echo "Warning: ${FILE} is already extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
PREFIX="${PREFIX}-ddn"

./bootstrap
H5DIR="$(readlink -f $(dirname $(which h5dump))/..)"
MPIDIR="$(readlink -f $(dirname $(which mpiexec))/..)"
set -x
export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/include"
export LDFLAGS="-Wl,-rpath=${MPIDIR}/lib -L$MPIDIR}/lib -L${H5DIR}/lib -lgpfs" \
export CFLAGS="-I$MPIDIR}/include -I${H5DIR}/include -I/usr/include" \
echo ${SRCdir}
make clean
./configure \
	--prefix="${PREFIX}" \
    --with-ime \
	--with-lustre \
	--with-mpiio \
	--with-posix
set +x
make -j${THREAD_NUM}
make install

