#!/bin/bash

module purge
module load openmpi/gnu/2.0.2
module load betke/hdf5/1.8.20
module list


SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

export NAME="ior"
export MAJOR="1"
export MINOR="10"
export REVISION="0-alpha0"
#export VERSION="$MAJOR.$MINOR.$REVISION"
export VERSION="git"


source ${SCRIPTPATH}/config

### CLONE ###
if [ ! -d "${CACHEDdir}/${SRCdir}" ]
then  
	mkdir "${CACHEDIR}/$SRCdir"
	git clone https://github.com/LLNL/ior.git "${CACHEDIR}/$SRCdir"
	#git clone git@github.com:IOR-LANL/ior.git "${CACHEDIR}/$SRCdir"
else
	echo "Warning: ${FILE} is already extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
echo "prefix: ${PREFIX}"

./bootstrap
H5DIR="$(readlink -f $(dirname $(which h5dump))/..)"
export LDFLAGS="-L${H5DIR}/lib -lgpfs" \
export CFLAGS="-I${H5DIR}/include" \
echo ${SRCdir}
./configure \
	--prefix="${PREFIX}" \
	--with-hdf5 \
	--with-lustre \
	--with-mpiio \
	--with-posix
make -j${THREAD_NUM}
make install

