#!/bin/bash

module purge
#module load betke/openssl/1.0.2f
#module load betke/curl/4.47.1
#module load openmpi/gnu/2.0.2
module load betke/hdf5/1.8.20
module list

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`
${SCRIPTPATH}/precheck

### CONFIG
NAME="netcdf"
MAJOR="4"
MINOR="4"
REVISION="1"
VERSION="$MAJOR.$MINOR.$REVISION"

source ${SCRIPTPATH}/config

FILE="v$MAJOR.$MINOR.$REVISION.tar.gz"
H5DIR="$(readlink -f $(dirname $(which h5dump))/..)"

### FETCH ###
cd ${CACHEdir}
if [ ! -e "${FILE}" ] 
then
 wget "https://github.com/Unidata/netcdf-c/archive/$FILE"
else
 echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi

SRCdir="${CACHEdir}/${NAME}-c-$VERSION"

### EXTRACT ###
if [ ! -d "${SRCdir}" ]
then
 mkdir "${SRCdir}"
 tar -vzxf "./$FILE"
else
 echo "Warning: ${NAME}-${VERSION} is already extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
make clean
export CC="mpicc"
export LDFLAGS="-L${H5DIR}/lib -Wl,--rpath=${H5DIR}/lib"
#export CPPFLAGS="-g -I${H5DIR}/include"
#export CFLAGS="-g -I${H5DIR}/include"
export CPPFLAGS="-I${H5DIR}/include"
export CFLAGS="-I${H5DIR}/include"

./configure \
 --enable-remote-fortran-bootstrap \
 --prefix=${PREFIX} \
 --enable-shared \
 --enable-static \
 --enable-parallel-tests \
 --enable-large-file-tests \
 --with-temp-large="$HOME/tmp" \
 --enable-pnetcdf 

make -j${THREAD_NUM}
make install

