#!/bin/bash

export NAME="rlm"
export VERSION="12.1BL3"
source ./config

#declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" "xios" "esmf/7.0.2" "psyclone/1.4.1" )
#deps=("")

fetch_local "$ROOT_DIR/download/rlm64.zip"

function build_script {
  set -x
	mkdir -p $PREFIX/bin
	mv rlm64/* $PREFIX/bin
	set +x
}

build_with build_script

module_init
#module_deps "${deps[@]}"
auto_module_paths
