#!/bin/bash

export NAME="breeze_healthcheck"
export VERSION="2.11.2"
source ./config

#declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" "xios" "esmf/7.0.2" "psyclone/1.4.1" )
deps=("")

fetch_http "https://webapp01.ellexus.com/download?key=341723A362E1BFE98CA8CDC74D4DBA96&pid=6&file=1"


function build_script {
  set -x
	cd breeze_2.11.2_x86_64
	module_load "${deps[@]}"
	set +x
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
