#!/bin/bash

export NAME="glibc"
export VERSION="2.23"
source ./config

#fetch_http "http://ftp.gnu.org/gnu/libc/glibc-${VERSION}.tar.gz"

    #"gcc-10.2.0-gcc-7.1.0-3o6mwwu" \
    #"binutils-2.35.1-gcc-10.2.0-4wl7bqg" \
declare -a load=( \
    "gcc/7.1.0" \
    "binutils-2.35.1-gcc-7.1.0-h6oupkx" \
    "cmake" \
    "automake" \
    "autoconf" \
    "libtool" \
    "python/3.5.2" \
    "k202107/bison" \
    )


declare -a deps=( "" )

function build_script {
	module_load "${load[@]}"
	module_load "${deps[@]}"

	set -x
	cd glibc-$VERSION

    #rm build -rf
    #mkdir build
    cd build

    #../configure \
        #--prefix=${PREFIX} || die "configure failed"

    export CFLAGS="-Wno-int-in-bool-context"
    export CPPFLAGS="-Wno-int-in-bool-context"

	make -j $THREAD_NUM || die "compile failed"
	make install  -j $THREAD_NUM || die "install failed"
	set +x
}

build_with build_script

module_init
module_deps "${deps[@]}"
auto_module_paths
