#!/bin/bash

export NAME="mosh"
export VERSION="1.3.2"
source ./config

declare -a deps=( "mpich/3.2" "hdf5/1.8.20" "netcdf/4.5.0" "netcdf_fortran/4.4.4" "xios" "esmf/7.0.2" "psyclone/1.4.1" )
deps=("")

fetch_http "https://mosh.org/mosh-1.3.2.tar.gz"

function build_script {
  set -x
	cd mosh-1.3.2
	module_load "${deps[@]}"
    ./configure || die "Couldn't configure"
    make || die "Couldn't make"
    make install || die "Couldn't install"
	set +x
}

build_with build_script

module_init
#module_deps "${deps[@]}"
auto_module_paths
