#!/bin/bash

SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

export NAME="hdf5"
export MAJOR="1"
export MINOR="8"
export REVISION="20"
export VERSION="$MAJOR.$MINOR.$REVISION"


module purge
module load ddn/mvapich/3.1.4
module list 


source ${SCRIPTPATH}/config


### FETCH ###
FILE="$NAME-$VERSION.tar.bz2"

if [ ! -e "${CACHEdir}/${FILE}" ] 
then
	wget -O ${CACHEdir}/${FILE} http://www.hdfgroup.org/ftp/HDF5/current/src/$FILE
	#wget -O "${CACHEdir}/${FILE}" http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-$MAJOR.$MINOR/hdf5-$VERSION/src/$FILE
else
	echo "WARNING: ${FILE} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "${CACHEDdir}/${SRCdir}" ]
then 
	tar -C ${CACHEdir} -xjvf "${CACHEdir}/${FILE}"
else
	echo "Warning: ${FILE} is already extracted"
fi


### COMPILE AND INSTALL ###
PREFIX="${PREFIX}-ddn"
cd ${SRCdir}
./configure --prefix="${PREFIX}" \
	--enable-production \
	--enable-hl \
	--enable-shared \
	--enable-static \
	--enable-parallel \
	CC="mpicc" \
	CXX="mpic++"

	#--enable-fortran  \
	#FC="mpif90" \
	#F77="mpif77" \
	#--enable-fortran \
	#--enable-fortran2003 \
	#CFLAGS="-g3 -O0" \
	#CXXFLAGS="-g3 -O0"
	#--enable-debug=all \
		
make -j${THREAD_NUM}
make install
